### ISSUE TITLE
Incorrect rendering behavior during window resize

### ISSUE THREAD

**Issue by LaylBongers** [athena-org/phosphorus#2]
**Expected behavior**
When window is resized to smaller, the background scales appropriately.

**Actual behavior**
When window is resized to smaller, the background shrinks faster than the window.

**Comment by LaylBongers** [comment]
Was introduced by pull request https://github.com/athena-org/phosphorus/pull/1

**Comment by LaylConway** [comment]
Was introduced by pull request https://github.com/athena-org/phosphorus/pull/1
